name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
 
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # Add steps to deploy the project here
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Azure CLI
        run: npm install -g azure-cli
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: Deploy Bicep
        run: az deployment group create -g <resource group name> --template-file main.bicep --parameters parameters.json --parameters MYSECRET=${{ secrets.MYSECRET }}
